### ISSUE TITLE
ReadRows merge acceptance tests

### ISSUE THREAD

**Issue by igorbernstein2** [bzzt/bigtable#8]
**Is your feature request related to a problem? Please describe.**
Hi,
I've been working on a new java client for bigtable and ran across this repo. I would like to thank you creating this client. I think it's a great addition to the Bigtable ecosystem. While poking around I noticed that there some edge cases that weren't covered in this client's ReadRows implementation. For example, it doesn't appear like the reset flag is respected. 

**Describe the solution you'd like**
On the Cloud Bigtable team we created a json file to help test ReadRow chunk parsing and I wanted to let you know of its existence:
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/test/resources/com/google/cloud/bigtable/data/v2/stub/readrows/read-rows-acceptance-test.json
Each test case has a list of chunks and the expected Row results. 

**Additional context**
Here are a couple of links of other clients using the file:
- [java](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsMergingAcceptanceTest.java)
- [golang](https://github.com/googleapis/google-cloud-go/blob/master/bigtable/reader_test.go#L205-L350)
- [python](https://github.com/googleapis/google-cloud-python/blob/master/bigtable/tests/unit/test_row_data.py)

Thanks again for publishing this client!

**Comment by jscott22** [comment]
Thanks for the input! I'll definitely take a look at your acceptance tests and make sure I cover all of them. Any future input or advice as I expand upon the library would be greatly appreciated.

**Comment by igorbernstein2** [comment]
If you plan on implementing retries, here are a few things to watch out for:
- For ReadRows make sure to track both the last merged row key and the last_scanned_row_key. So that you can skip over any filtered out rows on stream resumption
- There is a gotcha with ServerStreaming RPCs, where they can send all of their data but return an error status code. This is particularly dangerous with ReadRows, where if you aren't careful the resumption request can end up being empty triggering a full table scan.
- Try to avoid using serverside timestamps. They prevent mutations from being idempotent

In terms of default timeouts and retry counts, I would recommend to track [gapic configs](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/bigtable_gapic.yaml).

Unfortunately, since I'm not familiar with elixir, I don't have anything more specific. If you have any further questions, feel free to ping me.
